### ISSUE TITLE
doesn't work if content starts with "<!doctype html>"

### ISSUE THREAD

**Issue by uvtc** [sogaiu/janet-xmlish#1]
I'd like to parse a pretty clean machine-generated html file, but it starts with `<!doctype html>`.

**Comment by sogaiu** [comment]
@uvtc Do you have a sample I might take a look at?

**Comment by uvtc** [comment]
Sure. In an empty dir, I git clone this repo, then created the following script:

~~~janet
#!/usr/bin/env janet

(import ./janet-xmlish/janet-xmlish/grammar :as xg)

(def x (peg/match
        xg/xmlish-peg
        ``
        <!doctype html>
        <html>
        <body>
        <a href="https://janet-lang.org/">Janet Home Page</a>
        </body>
        </html>
        ``))

(pp x)
~~~

If I delete that "`<!doctype html>`" line, it works (prints out a ds). With it as is, it prints nil.

**Comment by uvtc** [comment]
Interestingly enough, if I start the html content sample with a blank line, it does the same thing (prints out nil).

**Comment by sogaiu** [comment]
@uvtc Thanks for the sample.

I tried adding some very simple handling of `doctype` in 2cf042c4729e8ffce5abc09b8b6e2ec22e944756 -- may be you could give that a try.

**Comment by tionis** [comment]
Let me extend this issue:
xmlish generally doesn't handle the first line well.
Example:
```xml
<?xml version='1.0' encoding='utf-8'?>
<some>
  <xml>
    here
  </xml>
</some>
```

**Comment by sogaiu** [comment]
@tionis Thanks for the report.

I think the reason the example you posted doesn't work is because it uses single quotes instead of double quotes.  Single quotes appear to be allowed: https://stackoverflow.com/questions/6800467/quotes-in-xml-single-or-double but I didn't account for it.

I'll have a look at trying to also support single quotes, but would you mind making a separate issue?  What appears to be happening for the example you posted doesn't seem to be related that closely to the original issue.

**Comment by tionis** [comment]
Ok, I created one in #2

**Comment by tionis** [comment]
And thanks for your quick response

**Comment by sogaiu** [comment]
Thanks!

**Comment by sogaiu** [comment]
@uvtc I think since https://github.com/sogaiu/janet-xmlish/commit/2cf042c4729e8ffce5abc09b8b6e2ec22e944756 things have been working on my end.  FWIW, [here](https://github.com/sogaiu/janet-xmlish/blob/2cf042c4729e8ffce5abc09b8b6e2ec22e944756/janet-xmlish/grammar.janet#L107-L126) is an example that worked for me.

I'm going to close this issue now, but please re-open if you find things aren't working for you.
